# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: winzent_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15winzent_message.proto\"\xbb\x01\n\x0eWinzentMessage\x12\x10\n\x08msg_type\x18\x01 \x01(\x05\x12\x0b\n\x03ttl\x18\x02 \x01(\x05\x12\x11\n\ttime_span\x18\x03 \x03(\x03\x12\n\n\x02id\x18\x04 \x01(\t\x12\x0e\n\x06sender\x18\x05 \x01(\t\x12\x11\n\tis_answer\x18\x06 \x01(\x08\x12\r\n\x05value\x18\x07 \x03(\x05\x12\x11\n\tanswer_to\x18\x08 \x01(\t\x12\x10\n\x08receiver\x18\t \x01(\t\x12\x14\n\x0c\x65thics_score\x18\n \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'winzent_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_WINZENTMESSAGE']._serialized_start = 26
    _globals['_WINZENTMESSAGE']._serialized_end = 213
# @@protoc_insertion_point(module_scope)
